# Generated by Django 2.2.6 on 2020-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201203_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Это должна быть картинка', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
