# Generated by Django 2.2.6 on 2020-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201211_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, help_text='Файл должен быть в расширении .mp3', null=True, upload_to='posts/', verbose_name='Музыкальный файл'),
        ),
    ]
